// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!!! THIS FILE IS GENERATED AUTOMATICALLY, DO NOT CHANGE IT !!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
/*
 *  ARDroneGeneratedTypes.h
 *  ARDroneEngine
 *
 *  Automatically generated.
 *  Copyright 2010 Parrot SA. All rights reserved.
 *
 */
#ifndef _ARDRONE_GENERATED_TYPES_H_
#define _ARDRONE_GENERATED_TYPES_H_

../../ARDroneLib/Soft/Common/navdata_common.h:#define NB_NAVDATA_DETECTION_RESULTS 4

typedef enum {
../../ARDroneLib/Soft/Common/led_animation.h:LED_ANIMATION(BLINK_GREEN_RED,{0,2,{{0x55,500},{0xAA,500}}})
../../ARDroneLib/Soft/Common/led_animation.h:LED_ANIMATION(BLINK_GREEN,{0,2,{{0x00,500},{0xAA,500}}})
../../ARDroneLib/Soft/Common/led_animation.h:LED_ANIMATION(BLINK_RED,{0,2,{{0x55,500},{0x00,500}}})
../../ARDroneLib/Soft/Common/led_animation.h:LED_ANIMATION(BLINK_ORANGE,{0,2,{{0xFF,500},{0x00,500}}})
../../ARDroneLib/Soft/Common/led_animation.h:LED_ANIMATION(SNAKE_GREEN_RED,{0,8,{{0x90,200},{0x48,200},{0x24,200},{0x12,200},{0x9,200},{0x84,200},{0x42,200},{0x21,200}}})
../../ARDroneLib/Soft/Common/led_animation.h:LED_ANIMATION(FIRE,{0,2,{{0x35,50},{0xC5,50}}})
../../ARDroneLib/Soft/Common/led_animation.h:LED_ANIMATION(STANDARD,{1,1,{{0xA5,100}}})
../../ARDroneLib/Soft/Common/led_animation.h:LED_ANIMATION(RED,{1,1,{{0x55,100}}})
../../ARDroneLib/Soft/Common/led_animation.h:LED_ANIMATION(GREEN,{1,1,{{0xAA,100}}})
../../ARDroneLib/Soft/Common/led_animation.h:LED_ANIMATION(RED_SNAKE,{0,4,{{0x40,500},{0x10,500},{0x04,500},{0x01,500}}})
../../ARDroneLib/Soft/Common/led_animation.h:LED_ANIMATION(BLANK,{1,1,{{0x00,100}}})
../../ARDroneLib/Soft/Common/led_animation.h:LED_ANIMATION(RIGHT_MISSILE,{1,5,{{0x00,500},{0x04,300},{0x1C,100},{0x30,300},{0x00,500}}})
../../ARDroneLib/Soft/Common/led_animation.h:LED_ANIMATION(LEFT_MISSILE,{1,5,{{0x00,500},{0x01,300},{0x43,100},{0xC0,300},{0x00,500}}})
../../ARDroneLib/Soft/Common/led_animation.h:LED_ANIMATION(DOUBLE_MISSILE,{1,5,{{0x00,500},{0x05,300},{0x5F,100},{0xF0,300},{0x00,500}}})
../../ARDroneLib/Soft/Common/led_animation.h:LED_ANIMATION(FRONT_LEFT_GREEN_OTHERS_RED,{1,1,{{0x95,100}}})
../../ARDroneLib/Soft/Common/led_animation.h:LED_ANIMATION(FRONT_RIGHT_GREEN_OTHERS_RED,{1,1,{{0x65,100}}})
../../ARDroneLib/Soft/Common/led_animation.h:LED_ANIMATION(REAR_RIGHT_GREEN_OTHERS_RED,{1,1,{{0x59,100}}})
../../ARDroneLib/Soft/Common/led_animation.h:LED_ANIMATION(REAR_LEFT_GREEN_OTHERS_RED,{1,1,{{0x56,100}}})
../../ARDroneLib/Soft/Common/led_animation.h:LED_ANIMATION(LEFT_GREEN_RIGHT_RED,{1,1,{{0x96,100}}})
../../ARDroneLib/Soft/Common/led_animation.h:LED_ANIMATION(LEFT_RED_RIGHT_GREEN,{1,1,{{0x69,100}}})
../../ARDroneLib/Soft/Common/led_animation.h:LED_ANIMATION(BLINK_STANDARD,{0,2,{{0x00,500},{0xA5,500}}})
} ARDRONE_LED_ANIMATION;

typedef enum {
../../ARDroneLib/Soft/Common/config.h:ARDRONE_ANIM_PHI_M30_DEG=0,
../../ARDroneLib/Soft/Common/config.h:ARDRONE_ANIM_PHI_30_DEG,
../../ARDroneLib/Soft/Common/config.h:ARDRONE_ANIM_THETA_M30_DEG,
../../ARDroneLib/Soft/Common/config.h:ARDRONE_ANIM_THETA_30_DEG,
../../ARDroneLib/Soft/Common/config.h:ARDRONE_ANIM_THETA_20DEG_YAW_200DEG,
../../ARDroneLib/Soft/Common/config.h:ARDRONE_ANIM_THETA_20DEG_YAW_M200DEG,
../../ARDroneLib/Soft/Common/config.h:ARDRONE_ANIM_TURNAROUND,
../../ARDroneLib/Soft/Common/config.h:ARDRONE_ANIM_TURNAROUND_GODOWN,
../../ARDroneLib/Soft/Common/config.h:ARDRONE_ANIM_YAW_SHAKE,
../../ARDroneLib/Soft/Common/config.h:ARDRONE_ANIM_YAW_DANCE,
../../ARDroneLib/Soft/Common/config.h:ARDRONE_ANIM_PHI_DANCE,
../../ARDroneLib/Soft/Common/config.h:ARDRONE_ANIM_THETA_DANCE,
../../ARDroneLib/Soft/Common/config.h:ARDRONE_ANIM_VZ_DANCE,
../../ARDroneLib/Soft/Common/config.h:ARDRONE_ANIM_WAVE,
../../ARDroneLib/Soft/Common/config.h:ARDRONE_ANIM_PHI_THETA_MIXED,
../../ARDroneLib/Soft/Common/config.h:ARDRONE_ANIM_DOUBLE_PHI_THETA_MIXED,
} ARDRONE_ANIMATION;

typedef enum {
../../ARDroneLib/Soft/Common/ardrone_api.h:CAD_TYPE_HORIZONTAL=0,
../../ARDroneLib/Soft/Common/ardrone_api.h:CAD_TYPE_VERTICAL,
../../ARDroneLib/Soft/Common/ardrone_api.h:CAD_TYPE_VISION,
../../ARDroneLib/Soft/Common/ardrone_api.h:CAD_TYPE_NONE,
../../ARDroneLib/Soft/Common/ardrone_api.h:CAD_TYPE_COCARDE,
../../ARDroneLib/Soft/Common/ardrone_api.h:CAD_TYPE_ORIENTED_COCARDE,
../../ARDroneLib/Soft/Common/ardrone_api.h:CAD_TYPE_STRIPE,
../../ARDroneLib/Soft/Common/ardrone_api.h:CAD_TYPE_H_COCARDE,
../../ARDroneLib/Soft/Common/ardrone_api.h:CAD_TYPE_H_ORIENTED_COCARDE,
../../ARDroneLib/Soft/Common/ardrone_api.h:CAD_TYPE_STRIPE_V,
../../ARDroneLib/Soft/Common/ardrone_api.h:CAD_TYPE_MULTIPLE_DETECTION_MODE,
../../ARDroneLib/Soft/Common/ardrone_api.h:CAD_TYPE_CAP,
../../ARDroneLib/Soft/Common/ardrone_api.h:CAD_TYPE_NUM,
} ARDRONE_CAMERA_DETECTION_TYPE;

typedef enum {
../../ARDroneLib/Soft/Common/ardrone_api.h:ARDRONE_VIDEO_CHANNEL_FIRST=0,
../../ARDroneLib/Soft/Common/ardrone_api.h:ARDRONE_VIDEO_CHANNEL_HORI=ARDRONE_VIDEO_CHANNEL_FIRST,
../../ARDroneLib/Soft/Common/ardrone_api.h:ARDRONE_VIDEO_CHANNEL_VERT,
../../ARDroneLib/Soft/Common/ardrone_api.h:ARDRONE_VIDEO_CHANNEL_LARGE_HORI_SMALL_VERT,
../../ARDroneLib/Soft/Common/ardrone_api.h:ARDRONE_VIDEO_CHANNEL_LARGE_VERT_SMALL_HORI,
../../ARDroneLib/Soft/Common/ardrone_api.h:ARDRONE_VIDEO_CHANNEL_LAST=ARDRONE_VIDEO_CHANNEL_LARGE_VERT_SMALL_HORI,
../../ARDroneLib/Soft/Common/ardrone_api.h:ARDRONE_VIDEO_CHANNEL_NEXT,
} ARDRONE_VIDEO_CHANNEL;

typedef enum {
../../ARDroneLib/Soft/Common/ardrone_api.h:ARDRONE_VARIABLE_BITRATE_MODE_DISABLED=0,
../../ARDroneLib/Soft/Common/ardrone_api.h:ARDRONE_VARIABLE_BITRATE_MODE_DYNAMIC,
../../ARDroneLib/Soft/Common/ardrone_api.h:ARDRONE_VARIABLE_BITRATE_MANUAL
} ARDRONE_VARIABLE_BITRATE;

typedef enum {
../../ARDroneLib/Soft/Common/ardrone_api.h:ARDRONE_ENEMY_COLOR_ORANGE_GREEN=1,
../../ARDroneLib/Soft/Common/ardrone_api.h:ARDRONE_ENEMY_COLOR_ORANGE_YELLOW,
../../ARDroneLib/Soft/Common/ardrone_api.h:ARDRONE_ENEMY_COLOR_ORANGE_BLUE,
../../ARDroneLib/Soft/Common/ardrone_api.h:ARDRONE_ENEMY_COLOR_ARRACE_FINISH_LINE=0x10,
../../ARDroneLib/Soft/Common/ardrone_api.h:ARDRONE_ENEMY_COLOR_ARRACE_DONUT=0x11
} ARDRONE_ENEMY_COLOR;

typedef enum {
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("GENERAL",VIDEO_ENABLE,INI_BOOLEAN,BOOL_T,BOOL_T*,(K_READ|K_WRITE),0,TRUE,DEFAULT_CONFIG_CALLBACK,CAT_COMMON)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("CONTROL",CONTROL_LEVEL,INI_INT,INT32_T,INT32_T*,(K_READ|K_WRITE),(K_READ|K_WRITE),0,DEFAULT_CONFIG_CALLBACK,CAT_APPLI)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("CONTROL",SHIELD_ENABLE,INI_INT,INT32_T,INT32_T*,(K_READ|K_WRITE),0,1,DEFAULT_CONFIG_CALLBACK,CAT_COMMON)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("CONTROL",EULER_ANGLE_MAX,INI_FLOAT,FLOAT32_T,FLOAT32_T*,(K_READ|K_WRITE),(K_READ|K_WRITE),DEFAULT_EULER_ANGLE_REF_MAX,CONTROL_CHANGED_CONFIG_CALLBACK,CAT_USER)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("CONTROL",ALTITUDE_MAX,INI_INT,INT32_T,INT32_T*,(K_READ|K_WRITE),0,DEFAULT_ALTITUDE_MAX,DEFAULT_CONFIG_CALLBACK,CAT_COMMON)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("CONTROL",ALTITUDE_MIN,INI_INT,INT32_T,INT32_T*,(K_READ|K_WRITE),0,DEFAULT_ALTITUDE_MIN,DEFAULT_CONFIG_CALLBACK,CAT_COMMON)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("CONTROL",CONTROL_TRIM_Z,INI_FLOAT,FLOAT32_T,FLOAT32_T*,(K_READ|K_WRITE),(K_READ|K_WRITE),DEFAULT_CONTROL_TRIM_Z,DEFAULT_CONFIG_CALLBACK,CAT_USER)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("CONTROL",CONTROL_IPHONE_TILT,INI_FLOAT,FLOAT32_T,FLOAT32_T*,(K_READ|K_WRITE),(K_READ|K_WRITE),DEFAULT_CONTROL_IPHONE_TILT,DEFAULT_CONFIG_CALLBACK,CAT_USER)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("CONTROL",CONTROL_VZ_MAX,INI_FLOAT,FLOAT32_T,FLOAT32_T*,(K_READ|K_WRITE),(K_READ|K_WRITE),DEFAULT_CONTROL_VZ_MAX,CONTROL_CHANGED_CONFIG_CALLBACK,CAT_USER)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("CONTROL",CONTROL_YAW,INI_FLOAT,FLOAT32_T,FLOAT32_T*,(K_READ|K_WRITE),(K_READ|K_WRITE),DEFAULT_CONTROL_YAW,CONTROL_CHANGED_CONFIG_CALLBACK,CAT_USER)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("CONTROL",OUTDOOR,INI_BOOLEAN,BOOL_T,BOOL_T*,(K_READ|K_WRITE),0,FALSE,CONTROL_CONFIG_CALLBACK,CAT_COMMON)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("CONTROL",FLIGHT_WITHOUT_SHELL,INI_BOOLEAN,BOOL_T,BOOL_T*,(K_READ|K_WRITE),0,FALSE,DEFAULT_CONFIG_CALLBACK,CAT_COMMON)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("CONTROL",BRUSHLESS,INI_BOOLEAN,BOOL_T,BOOL_T*,(K_READ|K_WRITE),0,TRUE,DEFAULT_CONFIG_CALLBACK,CAT_COMMON)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("CONTROL",AUTONOMOUS_FLIGHT,INI_BOOLEAN,BOOL_T,BOOL_T*,(K_READ|K_WRITE),0,FALSE,DEFAULT_CONFIG_CALLBACK,CAT_COMMON)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("CONTROL",MANUAL_TRIM,INI_BOOLEAN,BOOL_T,BOOL_T*,(K_READ|K_WRITE),(K_READ|K_WRITE),FALSE,DEFAULT_CONFIG_CALLBACK,CAT_USER)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("CONTROL",INDOOR_EULER_ANGLE_MAX,INI_FLOAT,FLOAT32_T,FLOAT32_T*,(K_READ|K_WRITE),(K_READ|K_WRITE),DEFAULT_EULER_ANGLE_REF_MAX,DEFAULT_CONFIG_CALLBACK,CAT_USER)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("CONTROL",INDOOR_CONTROL_VZ_MAX,INI_FLOAT,FLOAT32_T,FLOAT32_T*,(K_READ|K_WRITE),(K_READ|K_WRITE),DEFAULT_CONTROL_VZ_MAX,DEFAULT_CONFIG_CALLBACK,CAT_USER)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("CONTROL",INDOOR_CONTROL_YAW,INI_FLOAT,FLOAT32_T,FLOAT32_T*,(K_READ|K_WRITE),(K_READ|K_WRITE),DEFAULT_CONTROL_YAW,DEFAULT_CONFIG_CALLBACK,CAT_USER)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("CONTROL",OUTDOOR_EULER_ANGLE_MAX,INI_FLOAT,FLOAT32_T,FLOAT32_T*,(K_READ|K_WRITE),(K_READ|K_WRITE),DEFAULT_OUTDOOR_EULER_ANGLE_REF_MAX,DEFAULT_CONFIG_CALLBACK,CAT_USER)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("CONTROL",OUTDOOR_CONTROL_VZ_MAX,INI_FLOAT,FLOAT32_T,FLOAT32_T*,(K_READ|K_WRITE),(K_READ|K_WRITE),DEFAULT_OUTDOOR_CONTROL_VZ_MAX,DEFAULT_CONFIG_CALLBACK,CAT_USER)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("CONTROL",OUTDOOR_CONTROL_YAW,INI_FLOAT,FLOAT32_T,FLOAT32_T*,(K_READ|K_WRITE),(K_READ|K_WRITE),DEFAULT_OUTDOOR_CONTROL_YAW,DEFAULT_CONFIG_CALLBACK,CAT_USER)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("CONTROL",FLYING_MODE,INI_INT,INT32_T,INT32_T*,(K_READ|K_WRITE|K_NOBIND|K_SHALLOW),(K_READ|K_WRITE),0,FLYING_MODE_CONFIG_CALLBACK,CAT_SESSION)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_STR_A10("CONTROL",FLIGHT_ANIM,INI_STRING,STRING_T,CHAR*,(K_READ|K_WRITE|K_NOBIND|K_SHALLOW),0,"0,0",FLIGHT_ANIMATION_SELECTION_CALLBACK,CAT_COMMON)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_STR_A10("NETWORK",SSID_SINGLE_PLAYER,INI_STRING,STRING_T,CHAR*,(K_READ|K_WRITE),0,WIFI_NETWORK_NAME,DEFAULT_CONFIG_CALLBACK,CAT_COMMON)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_STR_A10("NETWORK",SSID_MULTI_PLAYER,INI_STRING,STRING_T,CHAR*,(K_READ|K_WRITE),0,WIFI_NETWORK_NAME,DEFAULT_CONFIG_CALLBACK,CAT_COMMON)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("NETWORK",WIFI_MODE,INI_INT,INT32_T,INT32_T*,(K_READ|K_WRITE),0,WIFI_MODE_INFRA,DEFAULT_CONFIG_CALLBACK,CAT_COMMON)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("NETWORK",SECURE,INI_BOOLEAN,BOOL_T,BOOL_T*,(K_READ|K_WRITE),0,0,DEFAULT_CONFIG_CALLBACK,CAT_COMMON)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_STR_A10("NETWORK",PASSKEY,INI_STRING,STRING_T,CHAR*,(K_READ|K_WRITE),0,"",DEFAULT_CONFIG_CALLBACK,CAT_COMMON)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_STR_A10("NETWORK",OWNER_MAC,INI_STRING,STRING_T,CHAR*,(K_READ|K_WRITE),0,NULL_MAC,OWNER_MAC_CALLBACK,CAT_COMMON)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("NETWORK",OWNER_IP_ADDRESS,INI_INT,UINT32_T,UINT32_T*,(K_READ|K_WRITE),0,0,DEFAULT_CONFIG_CALLBACK,CAT_COMMON)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("NETWORK",LOCAL_IP_ADDRESS,INI_INT,UINT32_T,UINT32_T*,(K_READ|K_WRITE),0,0,DEFAULT_CONFIG_CALLBACK,CAT_COMMON)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("NETWORK",BROADCAST_ADDRESS,INI_INT,UINT32_T,UINT32_T*,(K_READ|K_WRITE),0,0,DEFAULT_CONFIG_CALLBACK,CAT_COMMON)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("VIDEO",BITRATE,INI_INT,INT32_T,INT32_T*,(K_READ|K_SHALLOW),(K_READ|K_WRITE),0,DEFAULT_CONFIG_CALLBACK,CAT_APPLI)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("VIDEO",BITRATE_CTRL_MODE,INI_INT,INT32_T,INT32_T*,(K_READ|K_SHALLOW),(K_READ|K_WRITE),0,DEFAULT_CONFIG_CALLBACK,CAT_APPLI)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("VIDEO",VIDEO_CODEC,INI_INT,INT32_T,INT32_T*,(K_READ|K_SHALLOW),(K_READ|K_WRITE),UVLC_CODEC,CODEC_CONFIG_CALLBACK,CAT_APPLI)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("VIDEO",VIDEO_CHANNEL,INI_INT,INT32_T,INT32_T*,(K_READ|K_WRITE|K_NOBIND|K_SHALLOW),(K_READ|K_WRITE),0,VIDEO_CHANNEL_SELECTION_CALLBACK,CAT_SESSION)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_STR_A10("LEDS",LEDS_ANIM,INI_STRING,STRING_T,CHAR*,(K_READ|K_WRITE|K_NOBIND|K_SHALLOW),0,"0,0,0",LEDS_ANIMATION_SELECTION_CALLBACK,CAT_COMMON)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("DETECT",ENEMY_COLORS,INI_INT,INT32_T,INT32_T*,(K_READ|K_WRITE),0,DEFAULT_ENEMY_COLORS,DEFAULT_CONFIG_CALLBACK,CAT_COMMON)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("DETECT",GROUNDSTRIPE_COLORS,INI_INT,INT32_T,INT32_T*,(K_READ|K_WRITE),(K_READ|K_WRITE),DEFAULT_GROUNDSTRIPE_COLORS,DEFAULT_CONFIG_CALLBACK,CAT_SESSION)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("DETECT",ENEMY_WITHOUT_SHELL,INI_INT,INT32_T,INT32_T*,(K_READ|K_WRITE),0,0,DEFAULT_CONFIG_CALLBACK,CAT_COMMON)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("DETECT",DETECT_TYPE,INI_INT,INT32_T,INT32_T*,(K_READ|K_WRITE|K_NOBIND),(K_READ|K_WRITE|K_NOBIND),DEFAULT_DETECT_TYPE,DETECT_TYPE_CALLBACK,CAT_SESSION)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("DETECT",DETECTIONS_SELECT_H,INI_INT,INT32_T,INT32_T*,(K_READ|K_WRITE|K_NOBIND),(K_READ|K_WRITE),0,DETECTIONS_SELECT_CALLBACK,CAT_SESSION)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("DETECT",DETECTIONS_SELECT_V_HSYNC,INI_INT,INT32_T,INT32_T*,(K_READ|K_WRITE|K_NOBIND),(K_READ|K_WRITE),0,DETECTIONS_SELECT_CALLBACK,CAT_SESSION)
../../ARDRONELIB/SOFT/COMMON/CONFIG_KEYS.H:ARDRONE_CONFIG_KEY_IMM_A10("DETECT",DETECTIONS_SELECT_V,INI_INT,INT32_T,INT32_T*,(K_READ|K_WRITE|K_NOBIND),(K_READ|K_WRITE),0,DETECTIONS_SELECT_CALLBACK,CAT_SESSION)
} ARDRONE_CONFIG_KEYS;

typedef enum {
../../ARDroneLib/VLIB/video_codec.h:ARDRONE_VIDEO_CODEC_UVLC = 0x20,
../../ARDroneLib/VLIB/video_codec.h:ARDRONE_VIDEO_CODEC_P264 = 0x40,
} ARDRONE_VIDEO_CODEC;

typedef enum {
../../ARDroneLib/Soft/Common/ardrone_api.h:ARDRONE_FLYING_MODE_FREE_FLIGHT=0,
../../ARDroneLib/Soft/Common/ardrone_api.h:ARDRONE_FLYING_MODE_HOVER_ON_TOP_OF_ROUNDEL,
} ARDRONE_FLYING_MODE;
#endif // _ARDRONE_GENERATED_TYPES_H_
