// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!!! THIS FILE IS GENERATED AUTOMATICALLY, DO NOT CHANGE IT !!!!
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
/*
 *  ARDroneGeneratedCommandIn.h
 *  ARDroneEngine
 *
 *  Automatically generated.
 *  Copyright 2011 Parrot SA. All rights reserved
 *
 */

#ifdef COMMAND_IN_CONFIG_KEY
#ifdef COMMAND_IN_CONFIG_KEY_STRING
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_VIDEO_ENABLE, video_enable, int )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_CONTROL_LEVEL, control_level, int )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_SHIELD_ENABLE, shield_enable, int )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_EULER_ANGLE_MAX, euler_angle_max, float )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_ALTITUDE_MAX, altitude_max, int )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_ALTITUDE_MIN, altitude_min, int )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_CONTROL_TRIM_Z, control_trim_z, float )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_CONTROL_IPHONE_TILT, control_iphone_tilt, float )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_CONTROL_VZ_MAX, control_vz_max, float )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_CONTROL_YAW, control_yaw, float )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_OUTDOOR, outdoor, int )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_FLIGHT_WITHOUT_SHELL, flight_without_shell, int )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_BRUSHLESS, brushless, int )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_AUTONOMOUS_FLIGHT, autonomous_flight, int )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_MANUAL_TRIM, manual_trim, int )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_INDOOR_EULER_ANGLE_MAX, indoor_euler_angle_max, float )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_INDOOR_CONTROL_VZ_MAX, indoor_control_vz_max, float )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_INDOOR_CONTROL_YAW, indoor_control_yaw, float )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_OUTDOOR_EULER_ANGLE_MAX, outdoor_euler_angle_max, float )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_OUTDOOR_CONTROL_VZ_MAX, outdoor_control_vz_max, float )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_OUTDOOR_CONTROL_YAW, outdoor_control_yaw, float )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_FLYING_MODE, flying_mode, int )
COMMAND_IN_CONFIG_KEY_STRING (ARDRONE_CONFIG_KEY_FLIGHT_ANIM, flight_anim )
COMMAND_IN_CONFIG_KEY_STRING (ARDRONE_CONFIG_KEY_SSID_SINGLE_PLAYER, ssid_single_player )
COMMAND_IN_CONFIG_KEY_STRING (ARDRONE_CONFIG_KEY_SSID_MULTI_PLAYER, ssid_multi_player )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_WIFI_MODE, wifi_mode, int )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_SECURE, secure, int )
COMMAND_IN_CONFIG_KEY_STRING (ARDRONE_CONFIG_KEY_PASSKEY, passkey )
COMMAND_IN_CONFIG_KEY_STRING (ARDRONE_CONFIG_KEY_OWNER_MAC, owner_mac )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_OWNER_IP_ADDRESS, owner_ip_address, unsigned int )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_LOCAL_IP_ADDRESS, local_ip_address, unsigned int )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_BROADCAST_ADDRESS, broadcast_address, unsigned int )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_BITRATE, bitrate, int )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_BITRATE_CTRL_MODE, bitrate_ctrl_mode, int )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_VIDEO_CODEC, video_codec, int )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_VIDEO_CHANNEL, video_channel, int )
COMMAND_IN_CONFIG_KEY_STRING (ARDRONE_CONFIG_KEY_LEDS_ANIM, leds_anim )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_ENEMY_COLORS, enemy_colors, int )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_GROUNDSTRIPE_COLORS, groundstripe_colors, int )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_ENEMY_WITHOUT_SHELL, enemy_without_shell, int )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_DETECT_TYPE, detect_type, int )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_DETECTIONS_SELECT_H, detections_select_h, int )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_DETECTIONS_SELECT_V_HSYNC, detections_select_v_hsync, int )
COMMAND_IN_CONFIG_KEY (ARDRONE_CONFIG_KEY_DETECTIONS_SELECT_V, detections_select_v, int )
#endif //COMMAND_IN_CONFIG_KEY_STRING
#endif //COMMAND_IN_CONFIG_KEY
